export const EMPLOYEES = [
  {
    username: 'user1',
    firstName: 'John',
    lastName: 'Doe',
    email: 'john.doe1@example.com',
    birthDate: '1985-01-15',
    basicSalary: 50000,
    status: 'Active',
    group: 'Group1',
    description: 'Senior Developer',
  },
  {
    username: 'user2',
    firstName: 'Jane',
    lastName: 'Doe',
    email: 'jane.doe2@example.com',
    birthDate: '1990-02-25',
    basicSalary: 45000,
    status: 'Active',
    group: 'Group2',
    description: 'Project Manager',
  },
  {
    username: 'user3',
    firstName: 'Michael',
    lastName: 'Smith',
    email: 'michael.smith3@example.com',
    birthDate: '1983-03-12',
    basicSalary: 55000,
    status: 'Inactive',
    group: 'Group3',
    description: 'Business Analyst',
  },
  {
    username: 'user4',
    firstName: 'Mary',
    lastName: 'Johnson',
    email: 'mary.johnson4@example.com',
    birthDate: '1987-04-18',
    basicSalary: 47000,
    status: 'Active',
    group: 'Group4',
    description: 'HR Manager',
  },
  {
    username: 'user5',
    firstName: 'James',
    lastName: 'Williams',
    email: 'james.williams5@example.com',
    birthDate: '1979-05-22',
    basicSalary: 52000,
    status: 'Active',
    group: 'Group5',
    description: 'CTO',
  },
  {
    username: 'user6',
    firstName: 'Patricia',
    lastName: 'Brown',
    email: 'patricia.brown6@example.com',
    birthDate: '1992-06-15',
    basicSalary: 48000,
    status: 'Inactive',
    group: 'Group6',
    description: 'Marketing Manager',
  },
  {
    username: 'user7',
    firstName: 'Robert',
    lastName: 'Jones',
    email: 'robert.jones7@example.com',
    birthDate: '1986-07-19',
    basicSalary: 53000,
    status: 'Active',
    group: 'Group7',
    description: 'Sales Manager',
  },
  {
    username: 'user8',
    firstName: 'Linda',
    lastName: 'Garcia',
    email: 'linda.garcia8@example.com',
    birthDate: '1991-08-21',
    basicSalary: 46000,
    status: 'Active',
    group: 'Group8',
    description: 'Product Manager',
  },
  {
    username: 'user9',
    firstName: 'David',
    lastName: 'Martinez',
    email: 'david.martinez9@example.com',
    birthDate: '1984-09-10',
    basicSalary: 49000,
    status: 'Active',
    group: 'Group9',
    description: 'Finance Manager',
  },
  {
    username: 'user10',
    firstName: 'Barbara',
    lastName: 'Davis',
    email: 'barbara.davis10@example.com',
    birthDate: '1988-10-05',
    basicSalary: 51000,
    status: 'Inactive',
    group: 'Group10',
    description: 'Operations Manager',
  },
  {
    username: 'user11',
    firstName: 'William',
    lastName: 'Rodriguez',
    email: 'william.rodriguez11@example.com',
    birthDate: '1977-11-22',
    basicSalary: 54000,
    status: 'Active',
    group: 'Group1',
    description: 'IT Manager',
  },
  {
    username: 'user12',
    firstName: 'Elizabeth',
    lastName: 'Martinez',
    email: 'elizabeth.martinez12@example.com',
    birthDate: '1993-12-14',
    basicSalary: 47000,
    status: 'Active',
    group: 'Group2',
    description: 'Support Manager',
  },
  {
    username: 'user13',
    firstName: 'Joseph',
    lastName: 'Hernandez',
    email: 'joseph.hernandez13@example.com',
    birthDate: '1982-01-16',
    basicSalary: 49000,
    status: 'Inactive',
    group: 'Group3',
    description: 'Legal Manager',
  },
  {
    username: 'user14',
    firstName: 'Susan',
    lastName: 'Lopez',
    email: 'susan.lopez14@example.com',
    birthDate: '1986-02-26',
    basicSalary: 50000,
    status: 'Active',
    group: 'Group4',
    description: 'Compliance Manager',
  },
  {
    username: 'user15',
    firstName: 'Charles',
    lastName: 'Gonzalez',
    email: 'charles.gonzalez15@example.com',
    birthDate: '1981-03-19',
    basicSalary: 48000,
    status: 'Active',
    group: 'Group5',
    description: 'Logistics Manager',
  },
  {
    username: 'user16',
    firstName: 'Jessica',
    lastName: 'Wilson',
    email: 'jessica.wilson16@example.com',
    birthDate: '1994-04-17',
    basicSalary: 46000,
    status: 'Inactive',
    group: 'Group6',
    description: 'Training Manager',
  },
  {
    username: 'user17',
    firstName: 'Christopher',
    lastName: 'Anderson',
    email: 'christopher.anderson17@example.com',
    birthDate: '1980-05-11',
    basicSalary: 52000,
    status: 'Active',
    group: 'Group7',
    description: 'Quality Manager',
  },
  {
    username: 'user18',
    firstName: 'Karen',
    lastName: 'Thomas',
    email: 'karen.thomas18@example.com',
    birthDate: '1989-06-18',
    basicSalary: 47000,
    status: 'Active',
    group: 'Group8',
    description: 'Research Manager',
  },
  {
    username: 'user19',
    firstName: 'Daniel',
    lastName: 'Taylor',
    email: 'daniel.taylor19@example.com',
    birthDate: '1984-07-24',
    basicSalary: 49000,
    status: 'Inactive',
    group: 'Group9',
    description: 'Security Manager',
  },
  {
    username: 'user20',
    firstName: 'Nancy',
    lastName: 'Moore',
    email: 'nancy.moore20@example.com',
    birthDate: '1987-08-13',
    basicSalary: 51000,
    status: 'Active',
    group: 'Group10',
    description: 'Innovation Manager',
  },
  {
    username: 'user21',
    firstName: 'Matthew',
    lastName: 'Martin',
    email: 'matthew.martin21@example.com',
    birthDate: '1982-09-09',
    basicSalary: 53000,
    status: 'Active',
    group: 'Group1',
    description: 'Procurement Manager',
  },
  {
    username: 'user22',
    firstName: 'Ashley',
    lastName: 'Jackson',
    email: 'ashley.jackson22@example.com',
    birthDate: '1990-10-03',
    basicSalary: 46000,
    status: 'Active',
    group: 'Group2',
    description: 'Operations Manager',
  },
  {
    username: 'user23',
    firstName: 'Brian',
    lastName: 'White',
    email: 'brian.white23@example.com',
    birthDate: '1981-11-28',
    basicSalary: 54000,
    status: 'Active',
    group: 'Group3',
    description: 'Manufacturing Manager',
  },
  {
    username: 'user24',
    firstName: 'Dorothy',
    lastName: 'Harris',
    email: 'dorothy.harris24@example.com',
    birthDate: '1993-12-19',
    basicSalary: 47000,
    status: 'Inactive',
    group: 'Group4',
    description: 'Customer Service Manager',
  },
  {
    username: 'user25',
    firstName: 'Kevin',
    lastName: 'Clark',
    email: 'kevin.clark25@example.com',
    birthDate: '1983-01-14',
    basicSalary: 49000,
    status: 'Active',
    group: 'Group5',
    description: 'Facility Manager',
  },
  {
    username: 'user26',
    firstName: 'Michelle',
    lastName: 'Robinson',
    email: 'michelle.robinson26@example.com',
    birthDate: '1985-02-16',
    basicSalary: 50000,
    status: 'Inactive',
    group: 'Group6',
    description: 'Warehouse Manager',
  },
  {
    username: 'user27',
    firstName: 'Edward',
    lastName: 'Lewis',
    email: 'edward.lewis27@example.com',
    birthDate: '1980-03-14',
    basicSalary: 48000,
    status: 'Active',
    group: 'Group7',
    description: 'Supply Chain Manager',
  },
  {
    username: 'user28',
    firstName: 'Sarah',
    lastName: 'Young',
    email: 'sarah.young28@example.com',
    birthDate: '1992-04-12',
    basicSalary: 46000,
    status: 'Active',
    group: 'Group8',
    description: 'Risk Manager',
  },
  {
    username: 'user29',
    firstName: 'Steven',
    lastName: 'Walker',
    email: 'steven.walker29@example.com',
    birthDate: '1988-05-10',
    basicSalary: 52000,
    status: 'Inactive',
    group: 'Group9',
    description: 'Audit Manager',
  },
  {
    username: 'user30',
    firstName: 'Kimberly',
    lastName: 'Hall',
    email: 'kimberly.hall30@example.com',
    birthDate: '1986-06-06',
    basicSalary: 47000,
    status: 'Active',
    group: 'Group10',
    description: 'Talent Acquisition Manager',
  },
  {
    username: 'user31',
    firstName: 'Paul',
    lastName: 'Allen',
    email: 'paul.allen31@example.com',
    birthDate: '1979-07-25',
    basicSalary: 49000,
    status: 'Active',
    group: 'Group1',
    description: 'Production Manager',
  },
  {
    username: 'user32',
    firstName: 'Jessica',
    lastName: 'King',
    email: 'jessica.king32@example.com',
    birthDate: '1985-08-16',
    basicSalary: 50000,
    status: 'Inactive',
    group: 'Group2',
    description: 'E-commerce Manager',
  },
  {
    username: 'user33',
    firstName: 'Mark',
    lastName: 'Scott',
    email: 'mark.scott33@example.com',
    birthDate: '1980-09-18',
    basicSalary: 48000,
    status: 'Active',
    group: 'Group3',
    description: 'CRM Manager',
  },
  {
    username: 'user34',
    firstName: 'Nancy',
    lastName: 'Wright',
    email: 'nancy.wright34@example.com',
    birthDate: '1991-10-10',
    basicSalary: 46000,
    status: 'Active',
    group: 'Group4',
    description: 'Brand Manager',
  },
  {
    username: 'user35',
    firstName: 'Patrick',
    lastName: 'Mitchell',
    email: 'patrick.mitchell35@example.com',
    birthDate: '1987-11-14',
    basicSalary: 52000,
    status: 'Inactive',
    group: 'Group5',
    description: 'Community Manager',
  },
  {
    username: 'user36',
    firstName: 'Betty',
    lastName: 'Perez',
    email: 'betty.perez36@example.com',
    birthDate: '1984-12-18',
    basicSalary: 47000,
    status: 'Active',
    group: 'Group6',
    description: 'Customer Experience Manager',
  },
  {
    username: 'user37',
    firstName: 'Joshua',
    lastName: 'Roberts',
    email: 'joshua.roberts37@example.com',
    birthDate: '1978-01-12',
    basicSalary: 49000,
    status: 'Active',
    group: 'Group7',
    description: 'Partner Manager',
  },
  {
    username: 'user38',
    firstName: 'Margaret',
    lastName: 'Robinson',
    email: 'margaret.robinson38@example.com',
    birthDate: '1982-02-13',
    basicSalary: 50000,
    status: 'Inactive',
    group: 'Group8',
    description: 'Vendor Manager',
  },
  {
    username: 'user39',
    firstName: 'Edward',
    lastName: 'Green',
    email: 'edward.green39@example.com',
    birthDate: '1981-03-21',
    basicSalary: 48000,
    status: 'Active',
    group: 'Group9',
    description: 'Product Marketing Manager',
  },
  {
    username: 'user40',
    firstName: 'Barbara',
    lastName: 'Adams',
    email: 'barbara.adams40@example.com',
    birthDate: '1992-04-28',
    basicSalary: 46000,
    status: 'Active',
    group: 'Group10',
    description: 'Portfolio Manager',
  },
  {
    username: 'user41',
    firstName: 'Steven',
    lastName: 'Baker',
    email: 'steven.baker41@example.com',
    birthDate: '1988-05-19',
    basicSalary: 52000,
    status: 'Inactive',
    group: 'Group1',
    description: 'Innovation Manager',
  },
  {
    username: 'user42',
    firstName: 'Karen',
    lastName: 'Gonzales',
    email: 'karen.gonzales42@example.com',
    birthDate: '1990-06-17',
    basicSalary: 47000,
    status: 'Active',
    group: 'Group2',
    description: 'Global Marketing Manager',
  },
  {
    username: 'user43',
    firstName: 'Brian',
    lastName: 'Nelson',
    email: 'brian.nelson43@example.com',
    birthDate: '1981-07-22',
    basicSalary: 49000,
    status: 'Active',
    group: 'Group3',
    description: 'Corporate Development Manager',
  },
  {
    username: 'user44',
    firstName: 'Nancy',
    lastName: 'Carter',
    email: 'nancy.carter44@example.com',
    birthDate: '1994-08-11',
    basicSalary: 51000,
    status: 'Inactive',
    group: 'Group4',
    description: 'Learning and Development Manager',
  },
  {
    username: 'user45',
    firstName: 'Donald',
    lastName: 'Harris',
    email: 'donald.harris45@example.com',
    birthDate: '1982-09-16',
    basicSalary: 53000,
    status: 'Active',
    group: 'Group5',
    description: 'Client Success Manager',
  },
  {
    username: 'user46',
    firstName: 'Sandra',
    lastName: 'Thompson',
    email: 'sandra.thompson46@example.com',
    birthDate: '1987-10-20',
    basicSalary: 46000,
    status: 'Active',
    group: 'Group6',
    description: 'Public Relations Manager',
  },
];
